[project]
authors = [
    {name = "Logan Evans", email = "loganpevans@gmail.com"},
]
dependencies = [
    "mypy",
    "numpy",
    "matplotlib",
]
name = "redshift"
requires-python = ">=3.12"
version = "0.0.2"

